CREATE TABLE HISTOSAL (
    EMPNO INT,
    SAL NUMBER,
    DATE_CHANGE DATE,
    IDRUBRIQUE INT
);

CREATE SEQUENCE SEQ_HISTOSAL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RUB START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONF START WITH 1 INCREMENT BY 1;

CREATE TABLE RUBRIQUE(
    ID NUMBER PRIMARY KEY,
    VALEUR VARCHAR2(50),
    TYPERUB CHAR(1),
    MODE VARCHAR(50)
);

CREATE TABLE CONFIG(
    ID_RUB NUMBER PRIMARY KEY,
    MIN NUMBER,
    MAX NUMBER,
    VALEUR NUMBER
);

INSERT INTO CONFIG VALUES(3, 10, 60, 0.01);

INSERT INTO RUBRIQUE VALUES(1, 'BASE SALARY', 'G', 'FIXE');
INSERT INTO RUBRIQUE VALUES(2, 'ADVANTAGE', 'G', 'FIXE');
INSERT INTO RUBRIQUE VALUES(3, 'CNAPS', 'R', 'CALCUL');





-- HISTOSAL
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7369, 800.0,null, 1);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7369, 200.0 ,null, 2);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7369, 1.0 ,null, 3);

INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7499, 1600.0,null, 1);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7499, 400.0 ,null, 2);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7499, 1.0 ,null, 3);

INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7521, 1250.0 ,null, 1);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7521, 312.50 ,null, 2);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7521, 1.0 ,null, 3);

INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7566, 2975.0 ,null, 1);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7566, 743.75 ,null, 2);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7566, 1.0 ,null, 3);

INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7654, 1250.0 ,null, 1);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7654, 312.50 ,null, 2);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7654, 1.0 ,null, 3);

INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7698, 2850.0 ,null, 1);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7698, 712.50 ,null, 2);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7698, 1.0 ,null, 3);

INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7782, 2450.0 ,null, 1);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7782, 612.0 ,null, 2);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7782, 1.0 ,null, 3);

INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7788, 3000.0 ,null, 1);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7788, 750.0 ,null, 2);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7788, 1.0 ,null, 3);

INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7839, 5000.0 ,null, 1);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7839, 1250.0 ,null, 2);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7839, 1.0 ,null, 3);

INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7844, 1500.0 ,null, 1);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7844, 375.0 ,null, 2);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7844, 1.0 ,null, 3);

INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7876, 1100.0 ,null, 1);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7876, 275.0 ,null, 2);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7876, 1.0 ,null, 3);

INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7900, 950.0 ,null, 1);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7900, 237.50 ,null, 2);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7900, 1.0 ,null, 3);

INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7902, 3000.0 ,null, 1);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7902, 750.0 ,null, 2);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7902, 1.0 ,null, 3);

INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7934, 1300.0 ,null, 1);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7934, 325.0 ,null, 2);
INSERT INTO HISTOSAL (EMPNO, SAL,DATE_CHANGE ,IDRUBRIQUE) VALUES ( 7934, 1.0 ,null, 3);


COMMIT;


-- Employé 7369 : 15 janvier 2024
UPDATE HISTOSAL SET DATE_CHANGE = TO_DATE('2024-01-15','YYYY-MM-DD') WHERE EMPNO = 7369;

-- Employé 7499 : 10 février 2024
UPDATE HISTOSAL SET DATE_CHANGE = TO_DATE('2024-02-10','YYYY-MM-DD') WHERE EMPNO = 7499;

-- Employé 7521 : 20 mars 2024
UPDATE HISTOSAL SET DATE_CHANGE = TO_DATE('2024-03-20','YYYY-MM-DD') WHERE EMPNO = 7521;

-- Employé 7566 : 25 avril 2024
UPDATE HISTOSAL SET DATE_CHANGE = TO_DATE('2024-04-25','YYYY-MM-DD') WHERE EMPNO = 7566;

-- Employé 7654 : 30 mai 2024
UPDATE HISTOSAL SET DATE_CHANGE = TO_DATE('2024-05-30','YYYY-MM-DD') WHERE EMPNO = 7654;

-- Employé 7698 : 10 juillet 2024
UPDATE HISTOSAL SET DATE_CHANGE = TO_DATE('2024-07-10','YYYY-MM-DD') WHERE EMPNO = 7698;

-- Employé 7782 : 18 août 2024
UPDATE HISTOSAL SET DATE_CHANGE = TO_DATE('2024-08-18','YYYY-MM-DD') WHERE EMPNO = 7782;

-- Employé 7788 : 25 septembre 2024
UPDATE HISTOSAL SET DATE_CHANGE = TO_DATE('2024-09-25','YYYY-MM-DD') WHERE EMPNO = 7788;

-- Employé 7839 : 30 octobre 2024
UPDATE HISTOSAL SET DATE_CHANGE = TO_DATE('2024-10-30','YYYY-MM-DD') WHERE EMPNO = 7839;

-- Employé 7844 : 15 décembre 2024
UPDATE HISTOSAL SET DATE_CHANGE = TO_DATE('2024-12-15','YYYY-MM-DD') WHERE EMPNO = 7844;

-- Employé 7876 : 20 février 2025
UPDATE HISTOSAL SET DATE_CHANGE = TO_DATE('2025-02-20','YYYY-MM-DD') WHERE EMPNO = 7876;

-- Employé 7900 : 10 avril 2025
UPDATE HISTOSAL SET DATE_CHANGE = TO_DATE('2025-04-10','YYYY-MM-DD') WHERE EMPNO = 7900;

-- Employé 7902 : 18 juin 2025
UPDATE HISTOSAL SET DATE_CHANGE = TO_DATE('2025-06-18','YYYY-MM-DD') WHERE EMPNO = 7902;

-- Employé 7934 : 25 septembre 2025
UPDATE HISTOSAL SET DATE_CHANGE = TO_DATE('2025-09-25','YYYY-MM-DD') WHERE EMPNO = 7934;

 
 SELECT * FROM HISTOSAL H  JOIN RUBRIQUE R ON H.IDRUBRIQUE = R.ID JOIN CONFIG C ON R.ID = C.ID_RUB WHERE H.EMPNO = 7369 ORDER BY EMPNO;

COMMIT;
SELECT DATE_CHANGE FROM HISTOSAL H LEFT JOIN RUBRIQUE R ON H.IDRUBRIQUE = R.ID LEFT JOIN CONFIG C ON R.ID = C.ID_RUB WHERE H.EMPNO = 7369

SELECT H.EMPNO, H.SAL, H.DATE_CHANGE, H.IDRUBRIQUE, R.ID AS R_ID, R.VALEUR AS R_VALEUR, R.TYPERUB, R."MODE" AS R_MODE, C.ID_RUB AS C_ID_RUB, C."MIN" AS C_MIN, C."MAX" AS C_MAX, C.VALEUR AS C_VALEUR FROM HISTOSAL H LEFT JOIN RUBRIQUE R ON H.IDRUBRIQUE = R.ID LEFT JOIN CONFIG C ON R.ID = C.ID_RUB WHERE H.EMPNO = 7369;


SELECT H.EMPNO, H.SAL, H.DATE_CHANGE, H.IDRUBRIQUE, R.ID AS R_ID, R.VALEUR AS R_VALEUR, R.TYPERUB, R.MOD AS R_MODE, C.ID_RUB AS C_ID_RUB, C.MIN, C.MAX, C.VALEUR AS C_VALEUR FROM HISTOSAL H LEFT JOIN RUBRIQUE R ON H.IDRUBRIQUE = R.ID LEFT JOIN CONFIG C ON R.ID = C.ID_RUB WHERE H.EMPNO = 7369


            select * from HISTOSAL H JOIN RUBRIQUE R 



            SELECT H.EMPNO, H.SAL, H.DATE_CHANGE, H.IDRUBRIQUE, R.ID AS R_ID, R.VALEUR AS R_VALEUR, R.TYPERUB, R.MOD AS R_MOD, C.ID_RUB AS C_ID_RUB, C.MIN, C.MAX, C.VALEUR AS C_VALEUR FROM HISTOSAL H JOIN RUBRIQUE R ON H.IDRUBRIQUE = R.ID  JOIN CONFIG C ON R.ID = C.ID_RUB WHERE H.EMPNO = 7369


            SELECT * FROM HISTOSAL H J  JOIN CONFIG C ON R.ID = C.ID_RUB WHERE H.EMPNO = 7369



            SELECT 
    H.EMPNO,
    H.SAL,
    H.DATE_CHANGE,
    H.IDRUBRIQUE,
    R.ID AS R_ID,
    R.VALEUR AS R_VALEUR,
    R.TYPERUB,
    R.MOD AS R_MOD,
    C.ID_RUB AS C_ID_RUB,
    C.MIN AS C_MIN,
    C.MAX AS C_MAX,
    C.VALEUR AS C_VALEUR
FROM HISTOSAL H
LEFT JOIN RUBRIQUE R ON H.IDRUBRIQUE = R.ID
LEFT JOIN CONFIG C ON R.ID = C.ID_RUB
ORDER BY H.EMPNO, H.DATE_CHANGE DESC;


SELECT EMPNO, MAX(SAL) AS SAL, MAX(DATE_CHANGE) AS DATE_CHANGE, MAX(IDRUBRIQUE) AS IDRUBRIQUE FROM HISTOSAL WHERE DATE_CHANGE >= TO_DATE('01-01-2024', 'DD-MM-YYYY') GROUP BY EMPNO



CREATE SEQUENCE rub START WITH 1 INCREMENT BY 1;